### ISSUE TITLE
Latest version fails to build

### ISSUE THREAD

**Issue by phooijenga** [golangci/gofmt#7]
The latest version of this repository does not build:

```
$ go test ./...
package github.com/golangci/gofmt/gofmt
	gofmt/gofmt.go:17:2: use of internal package internal/diff not allowed
```

I believe this problem was introduced in f6ae7c7.

**Comment by egor-denysenko** [comment]
I'm also facing this issue, when could it be fixed?

**Comment by ldez** [comment]
I merged the PR but you should not update the dependencies of golangci-lint outside of the official release.

The dependencies can have an impact on golangci-lint, so the libs should stay at the version defined inside the `go.mod` of golangci-lint.

**Comment by egor-denysenko** [comment]
Thanks for the checking out the PR! 
Ok i'll wait for the next release of golangci-lint and in the mean time downgrade to a lower version of the tool
