### ISSUE TITLE
License

### ISSUE THREAD

**Issue by malte-behrendt-gr** [golangci/gofmt#9]
Thanks a lot for this awesome tool!

Can you please add a license?

According to [this](https://choosealicense.com/no-permission/#for-users), without a license I "have no permission from the creators of the software to use [...] the software"

And of course I'd love using it legally :-D

If you prefer a PR I'm also happy to create one with a LICENSE file.

**Comment by ldez** [comment]
Hello,

This repository only contains hard forks of gofmt and goimports used by [golangci-lint](https://github.com/golangci/golangci-lint):
- https://github.com/golangci/gofmt/tree/master/gofmt
- https://github.com/golangci/gofmt/tree/master/goimports

This is not the official [gofmt](https://github.com/golang/go) or the official [goimports](https://github.com/golang/go).

The licenses are already present and they are the same as the original tools:
- https://github.com/golangci/gofmt/blob/master/gofmt/LICENSE
- https://github.com/golangci/gofmt/blob/master/goimports/LICENSE
